"""empty message

Revision ID: 3f3432414ed3
Revises: None
Create Date: 2014-11-25 19:28:16.744962

"""

# revision identifiers, used by Alembic.
revision = '3f3432414ed3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.String(length=12), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirm')

    ### end Alembic commands ###
